### ISSUE TITLE
Error when loading hg38 reference genome

### ISSUE THREAD

**Issue by sgunz** [BoevaLab/CHIPIN#2]
## Bug description

When running the following command I get an error message:

`CHIPIN_normalize(path_to_bw=pathToFiles, type_norm="quantile", RPKM=pathToRPKMfile, sample_name=sampleName, output_dir=outputFolder, organism="hg38")`

> Error in CHIPIN_normalize(path_to_bw = bw_path, type_norm = "quantile",  : 
  object 'TSS_hg38' not found

## Proposed solution
When loading `data("TSS_hg38")` the resulting dataframe is called `hg38TSS` instead of `TSS_hg38`. Changing the following lines in the `functions_CHIPIN.R` file solved the problem for me.

line 1925:  from `D_TSS=TSS_hg38` into `D_TSS=hg38TSS`
line 2074: from `D_TSS=TSS_hg38` into `D_TSS=hg38TSS`

## Session Info

R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

**Comment by valeu** [comment]
Thank you Samuel, I have committed this change.
